# Data Pre-Processing

## Import the Libraries

In [1]:
### ----------------Library collection of functions and class to perform actions-------------------#######
import numpy as np                              ##to work with arrays
import matplotlib.pyplot as plt                                ##garphs and charts
import pandas as pd                                ## helps us import the dataset and also create matrix of features of dataset also(preprocess data)
                                                   #scikit-learn -->library that includes all models of data science


In [2]:
   #          if ever want to import from scikit use from sklear.whatever import whatever

## **Import Data**(here we use Pandas)

In [3]:
dataset=pd.read_csv('Data.csv')   # here we can also set the delimiter as ('name od dataset',delimiter=';')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1:].values


### or we can just specify the columns  or ke can drop the dependent feature column
So like -->  x=dats['sex','abc']
   --> x= df.drop('abc',axis=1)

In [4]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


## Missing Data in Dataset

### yaha do option hota h yaa toh ignore kr ke remove kr do yaaa column avg le ke replace

## Yaha ek or option h yaa toh pata h ki kaha missing h yaa tohh khud dhoond lo.

### Yourself wale maiii ka code ye h

In [6]:
missing_values=dataset.isnull().sum()
print("Missing data: \n",missing_values)

Missing data: 
 Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


#### start first by importing SimpleImputer from scikit-learn library

In [7]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
#imputer.fit(dataset)          # ye bas pata krte h
imputer.fit(x[:, 1:3])
x[:, 1:3]=imputer.transform(x[:, 1:3])    #transfor jo h wo actual kaam krta h mean calculate kr ke relace krne kaaa ye ek naya featureset column return krta h


In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding Variables(As in pata krna kis ke kis ko predict krna h)

### Independent Variables (ye sirf string wale ko krna h)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [10]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding Dependent Variable

In [11]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)

C:\Users\KIIT\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the Data

### Into Training and testing set

In [13]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2 , random_state=42)


In [14]:
print(x_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [15]:
print(x_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]]


In [16]:
print(y_train)

[1 0 1 0 1 1 0 0]


In [17]:
print(y_test)

[0 1]


# Feature Scaling(Done after spliting)

### Only required for some models

In [18]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
x_train[:, 3:]=sc.fit_transform(x_train[:, 3:])
x_test[:, 3:]=sc.transform(x_test[:, 3:])

In [19]:
print(x_train)

[[1.0 0.0 0.0 -0.7529426005471072 -0.6260377781240918]
 [1.0 0.0 0.0 1.008453807952985 1.0130429500553495]
 [1.0 0.0 0.0 1.7912966561752484 1.8325833141450703]
 [0.0 1.0 0.0 -1.7314961608249362 -1.0943465576039322]
 [1.0 0.0 0.0 -0.3615211764359756 0.42765697570554906]
 [0.0 1.0 0.0 0.22561095973072184 0.05040823668012247]
 [0.0 0.0 1.0 -0.16581046438040975 -0.27480619351421154]
 [0.0 0.0 1.0 -0.013591021670525094 -1.3285009473438525]]


In [20]:
print(x_test)

[[0.0 1.0 0.0 2.1827180802863797 2.3008920936249107]
 [0.0 0.0 1.0 -2.3186282969916334 -1.7968097268236927]]
